services:
  web:
    image: ${APP_IMAGE:?A variavel APP_IMAGE deve ser informada}
    container_name: app-container

    ports:
      - "8080:80"

    restart: unless-stopped

    networks:
      - webnet

    healthcheck:
      test:
        - CMD-SHELL
        - wget --quiet --spider http://127.0.0.1/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  webnet:
    driver: bridge