name: app CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
        
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v7

        - name: Validando arquivos
          run: |
            pwd
            ls -la
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v4
        - name: Build Dockerfile
          uses: docker/build-push-action@v7
          with:
            context: .
            file: ./docker/Dockerfile
            push: false
            load: true
            tags: app:${{ github.sha }}

        - name: Validando a imagem 
          run: |
            docker image ls
            docker container run --rm app:${{ github.sha }} ls -la

        - name: Smoke Test Simples
          run: |
            docker container run -d -p 8080:80 --name app-container app:${{ github.sha }} 
            sleep 10   
            docker container ls -a
            curl -f http://localhost:8080 || exit 1
            docker container rm -f app-container


            


            
        

