name: app CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
        
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v7

        - name: Validando arquivos
          run: |
            pwd
            ls -la
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v4
        - name: Build Dockerfile
          uses: docker/build-push-action@v7
          with:
            context: .
            file: ./docker/Dockerfile
            push: false
            tags: app:${{ github.sha }}



            
        

